import { useState } from 'react';
import type { ClientMsg, Player, Snapshot } from '../../shared/types';
import { money } from '../../shared/chips';
import { Chip } from '../components/Chips';
import '../styles/game.css';
export function JoinView({ snapshot, send, connected }: { snapshot: Snapshot; send: (msg: ClientMsg) => void; connected: boolean }) {
  const [name, setName] = useState(localStorage.getItem('poker-name') ?? ''), [seat, setSeat] = useState<number | null>(null);
  const [buyIn, setBuyIn] = useState(false);
  const { game } = snapshot, lobby = game.phase === 'lobby';
  const canBuyIn = game.players.filter(p => p.status !== 'busted').length < 8 && game.phase === 'hand-complete';
  const reclaim = (player: Player) => { localStorage.setItem('poker-name', player.name); send({ type: 'reclaimSeat', playerId: player.id }); };
  const seatForm = <form className="panel join-form" onSubmit={e => { e.preventDefault(); if (seat !== null) { localStorage.setItem('poker-name', name.trim()); send({ type: lobby ? 'claimSeat' : 'lateBuyIn', name, seat }); } }}><label className="field"><span className="label">What should we call you?</span><input aria-label="Your name" autoComplete="nickname" placeholder="Your name" maxLength={24} value={name} onChange={e => setName(e.target.value)}/></label><span className="label">Pick your seat</span><div className="seat-picker">{Array.from({ length: 8 }, (_, i) => { const occupant = game.players.find(p => p.seat === i && p.status !== 'busted'); return <button type="button" aria-label={`Seat ${i + 1}${occupant ? ` · ${occupant.name}` : ''}`} disabled={!!occupant} key={i} className={seat === i ? 'selected' : ''} onClick={() => setSeat(i)}><span>{String(i + 1).padStart(2, '0')}</span><small>{occupant ? occupant.name : 'Open'}</small></button>; })}</div>{!lobby && <p className="hint">Buy in with {money(game.config.startingStack)} in chips. You’ll play the next hand.</p>}<button className="primary full-width" type="submit" disabled={!connected || !name.trim() || seat === null || game.players.some(p => p.seat === seat && p.status !== 'busted')}>Take my seat →</button></form>;
  return <main className="join-page"><div className="join-emblem"><Chip value={100} color="#D4AF6A" size={80}/></div><span className="eyebrow">There’s a seat for you</span><h1>{lobby ? <>Pull up a chair<span>.</span></> : 'Who are you?'}</h1><p className="intro-subtitle">{game.config.name}<br/><span className="muted">{lobby ? '8 seats. One good night.' : 'Tap your name to take your seat and stack back.'}</span></p>
    {lobby && seatForm}
    {game.players.length > 0 && <section className="panel reclaim-panel" aria-label="Reclaim your seat"><h2>{lobby ? 'Already joined on another device?' : 'Take your seat back'}</h2><p className="hint">Choose your own name. Your seat, chips, and turn stay with you.</p><div className="reclaim-roster">{[...game.players].sort((a, b) => Number(a.connected) - Number(b.connected) || a.seat - b.seat).map(player => <button type="button" className="reclaim-player" key={player.id} disabled={!connected || player.connected} aria-label={`Reclaim ${player.name}, Seat ${player.seat + 1}`} onClick={() => reclaim(player)}><span className="reclaim-seat">Seat {player.seat + 1}</span><strong>{player.name}</strong><span>{money(player.stack)}</span><small className={player.connected ? 'reclaim-live' : ''}>{player.connected ? 'Live' : 'Offline'}</small></button>)}</div></section>}
    {!lobby && canBuyIn && <section className="late-buy-in"><button type="button" className="game-button" aria-expanded={buyIn} onClick={() => setBuyIn(value => !value)}>Join as a new player</button>{buyIn && seatForm}</section>}
    <a className="text-link" href="/board">Watch the table</a><p className="hint">Use your own cards. We’ll take care of the chips.</p>{lobby && snapshot.you.host && <a className="text-link" href="/setup">Hosting tonight? Set up your game →</a>}
  </main>;
}
