import { useEffect, useState } from 'react';
import type { ClientMsg, Config, Snapshot } from '../../shared/types';
import { blindLevel, validateConfig } from '../../shared/blinds';
import { money } from '../../shared/chips';
import { DenominationEditor } from '../components/DenominationEditor';
import { ChipStack } from '../components/Chips';
import { JoinQr } from '../components/JoinQr';
function NumberWell({ label, value, onChange, prefix = '$', step = 1 }: { label: string; value: number; onChange: (value: number) => void; prefix?: string; step?: number }) { return <label className="field"><span className="label">{label}</span><span className="value-well"><span>{prefix}</span><input aria-label={label} type="number" min="0" step={step} value={value || ''} onChange={e => onChange(Number(e.target.value))}/></span></label>; }
export function SetupView({ snapshot, send, connected }: { snapshot: Snapshot; send: (msg: ClientMsg) => void; connected: boolean }) {
  const [config, setConfig] = useState<Config>(() => { try { const saved = localStorage.getItem('poker-setup'); return saved ? { ...snapshot.game.config, ...JSON.parse(saved) } : snapshot.game.config; } catch { return snapshot.game.config; } });
  const [attempted, setAttempted] = useState(false);
  useEffect(() => { localStorage.setItem('poker-setup', JSON.stringify(config)); }, [config]);
  const set = <K extends keyof Config>(key: K, value: Config[K]) => setConfig(c => ({ ...c, [key]: value }));
  const errors = validateConfig(config), canStart = snapshot.game.players.length >= 2 && !errors.length && connected && snapshot.you.dealer;
  const previewable = config.denominations.every(d => d.value > 0) && config.multiplier >= 1 && config.smallBlind > 0 && config.bigBlind > 0;
  return <main className="setup-page"><div className="page-intro"><a className="back-link" href="/board">← Back to table</a><span className="eyebrow">A good night starts here</span><h1>Set the stakes<span>.</span></h1><p>Real cards. Good company. We’ll keep track of the chips.</p></div><form onSubmit={e => { e.preventDefault(); setAttempted(true); if (canStart) send({ type: 'startTournament', config }); }}>
    <label className="field game-name"><span className="label">Game name</span><input aria-label="Game name" maxLength={60} value={config.name} onChange={e => set('name', e.target.value)}/></label>
    <div className="setup-grid"><div className="setup-column"><JoinQr snapshot={snapshot} send={send} variant="large" /><DenominationEditor value={config.denominations} onChange={v => set('denominations', v)}/><section className="panel starting-panel"><span className="label">Starting chips · per player</span><div className="pills">{[20, 50, 100, 500].map(n => <button key={n} type="button" className={config.startingStack === n ? 'selected' : ''} onClick={() => set('startingStack', n)}>{money(n)}</button>)}</div><NumberWell label="Starting stack" value={config.startingStack} onChange={v => set('startingStack', v)}/><ChipStack amount={config.startingStack} denominations={config.denominations}/></section></div>
    <div className="setup-column"><section className="panel"><div className="section-heading"><div><span className="label">Keep the game moving</span><h2>Blinds & tempo</h2></div><span className="outline-chip">01</span></div><div className="two-cols"><NumberWell label="Small blind" value={config.smallBlind} onChange={v => set('smallBlind', v)}/><NumberWell label="Big blind" value={config.bigBlind} onChange={v => set('bigBlind', v)}/></div><div className="field"><span className="label">Blind level-up multiplier</span><div className="pills">{[1.5, 2, 2.5, 3].map(n => <button type="button" className={config.multiplier === n ? 'selected' : ''} key={n} onClick={() => set('multiplier', n)}>{n}×</button>)}</div></div><div className="two-cols"><NumberWell label="Custom multiplier" prefix="×" step={0.1} value={config.multiplier} onChange={v => set('multiplier', v)}/><NumberWell label="Level length (min)" prefix="◷" value={config.levelMinutes} onChange={v => set('levelMinutes', v)}/></div><details className="ante-settings"><summary>Antes <span className="muted">{config.ante ? money(config.ante) : 'Off'}</span></summary><label className="field"><span className="label">Ante style</span><select aria-label="Ante style" value={config.anteMode} onChange={e => set('anteMode', e.target.value as Config['anteMode'])}><option value="big-blind">Single big-blind ante</option><option value="per-player">Every player</option><option value="none">No ante</option></select></label><NumberWell label="Ante amount (level 1)" value={config.ante} onChange={v => set('ante', v)}/><p className="hint">Optional. Scales with the blinds; the big blind posts its blind first.</p></details></section>
    <section className="panel level-preview"><div className="section-heading"><h2>A look ahead</h2><span className="label">Blinds preview</span></div><table><thead><tr><th>Level</th><th>Small / big</th><th>Starts</th></tr></thead><tbody>{previewable && Array.from({ length: 5 }, (_, i) => { const b = blindLevel(config, i + 1); return <tr key={i}><td><span className={i === 0 ? 'level-dot current' : 'level-dot'}>{String(i + 1).padStart(2, '0')}</span>{i === 0 && <small>First hand</small>}</td><td>{money(b.small)} <span className="muted">/</span> {money(b.big)}</td><td>{i === 0 ? 'Now' : `${i * config.levelMinutes} min`}</td></tr>; })}</tbody></table><p className="hint">New blinds apply at the start of the next hand.</p></section></div></div>
    {errors.length > 0 && <div className="validation" role="status">{errors.map(e => <p key={e}>{e}</p>)}</div>}
    <div className="setup-footer"><div><strong>{snapshot.game.players.length} of 8 seats filled</strong><p className="hint">{snapshot.game.players.length < 2 ? 'At least two players need to join before you start.' : 'Everyone in? Let’s put the cards on the table.'}</p></div><button className="primary start-button" disabled={!canStart} type="submit">Start tournament <span>→</span></button></div>{attempted && !snapshot.you.dealer && <p className="validation">Only the host can start the tournament.</p>}
  </form></main>;
}
