import type { Denomination } from '../../shared/types';
import { CHIP_COLORS } from '../../shared/chips';
import { Chip } from './Chips';
export function DenominationEditor({ value, onChange }: { value: Denomination[]; onChange: (ds: Denomination[]) => void }) {
  const update = (i: number, patch: Partial<Denomination>) => onChange(value.map((d, j) => i === j ? { ...d, ...patch } : d));
  const add = () => { let next = Math.max(...value.map(d => d.value), 1) * 5; if (!Number.isFinite(next)) next = 100; onChange([...value, { value: next, color: CHIP_COLORS[value.length] }]); };
  return <section className="panel denomination-panel"><div className="section-heading"><div><span className="label">The essentials</span><h2>Chips <span className="muted">({value.length})</span></h2></div><div className="inline"><button type="button" className="circle" aria-label="Remove denomination" disabled={value.length <= 2} onClick={() => onChange(value.slice(0, -1))}>−</button><button type="button" className="circle gold" aria-label="Add denomination" disabled={value.length >= 8} onClick={add}>+</button></div></div>
    <div className="denomination-rows">{value.map((d, i) => <div className="denomination-row" key={i}><Chip value={d.value} color={d.color} size={58}/><label className="value-well"><span>$</span><input type="number" min="1" max="1000000" aria-label={`Chip ${i + 1} value`} value={d.value || ''} onChange={e => update(i, { value: Number(e.target.value) })}/></label><div className="swatches" aria-label={`Chip ${i + 1} color`}>{CHIP_COLORS.map((color, index) => <button type="button" key={color} title={['Cream', 'Red', 'Teal', 'Green', 'Black', 'Purple', 'Orange', 'Gold'][index]} aria-label={`Chip ${i + 1} ${['cream', 'red', 'teal', 'green', 'black', 'purple', 'orange', 'gold'][index]}`} aria-pressed={color === d.color} className={color === d.color ? 'swatch selected' : 'swatch'} style={{ '--swatch': color } as React.CSSProperties} onClick={() => update(i, { color })}/>)}</div></div>)}</div><p className="hint">Your chips, your colors. Every amount at the table is shown in these denominations.</p></section>;
}
